# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\caina\OneDrive\Área de Trabalho\calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.telaNumero = QtWidgets.QLCDNumber(self.centralwidget)
        self.telaNumero.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.telaNumero.setSmallDecimalPoint(False)
        self.telaNumero.setDigitCount(8)
        self.telaNumero.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.telaNumero.setObjectName("telaNumero")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 70, 281, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn1 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 0, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 0, 2, 1, 1)
        self.btnMais = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnMais.setFont(font)
        self.btnMais.setObjectName("btnMais")
        self.gridLayout.addWidget(self.btnMais, 0, 3, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 1, 0, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 1, 1, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 1, 2, 1, 1)
        self.btnMenos = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnMenos.setFont(font)
        self.btnMenos.setObjectName("btnMenos")
        self.gridLayout.addWidget(self.btnMenos, 1, 3, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 2, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 2, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 2, 2, 1, 1)
        self.btnDivide = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnDivide.setFont(font)
        self.btnDivide.setObjectName("btnDivide")
        self.gridLayout.addWidget(self.btnDivide, 2, 3, 1, 1)
        self.btn10 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn10.setFont(font)
        self.btn10.setObjectName("btn10")
        self.gridLayout.addWidget(self.btn10, 3, 0, 1, 1)
        self.btn100 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn100.setFont(font)
        self.btn100.setObjectName("btn100")
        self.gridLayout.addWidget(self.btn100, 3, 1, 1, 1)
        self.btnVezes = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnVezes.setFont(font)
        self.btnVezes.setObjectName("btnVezes")
        self.gridLayout.addWidget(self.btnVezes, 3, 2, 1, 1)
        self.btnIgual = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnIgual.setFont(font)
        self.btnIgual.setObjectName("btnIgual")
        self.gridLayout.addWidget(self.btnIgual, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.numero = 0
        self.resultado = 0

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.telaNumero.display(self.numero)

        self.btn1.clicked.connect(lambda: self.addDigito(1))
        self.btn2.clicked.connect(lambda: self.addDigito(2))
        self.btn3.clicked.connect(lambda: self.addDigito(3))
        self.btn4.clicked.connect(lambda: self.addDigito(4))
        self.btn5.clicked.connect(lambda: self.addDigito(5))
        self.btn6.clicked.connect(lambda: self.addDigito(6))
        self.btn7.clicked.connect(lambda: self.addDigito(7))
        self.btn8.clicked.connect(lambda: self.addDigito(8))
        self.btn9.clicked.connect(lambda: self.addDigito(9))
        self.btn10.clicked.connect(lambda: self.mulNumero(10))
        self.btn100.clicked.connect(lambda: self.mulNumero(100))
        self.btnMais.clicked.connect(self.addNumero)
        self.btnMenos.clicked.connect(self.subNumero)
        self.btnVezes.clicked.connect(self.multiNumero)
        self.btnDivide.clicked.connect(self.divNumero)
        self.btnIgual.clicked.connect(self.resolver)

    def addDigito(self, num:int):
        if len(str(self.numero)) < self.telaNumero.digitCount():
            self.numero = self.numero * 10 + num
            self.telaNumero.display(self.numero)

    def mulNumero(self, mult: int):
        self.numero = self.numero * mult

        if len(str(self.numero)) > self.telaNumero.digitCount():
            self.numero = self.numero / mult 
        
        self.telaNumero.display(self.numero)

    def addNumero(self):
        self.operacao = '+'
        self.resultado = self.numero
        self.numero = 0
        self.telaNumero.display(self.numero)
    
    def multiNumero(self):
        self.operacao = '*'
        self.resultado = self.numero
        self.numero = 0
        self.telaNumero.display(self.numero)

    def subNumero(self):
        self.operacao = '-'
        self.resultado = self.numero
        self.numero = 0
        self.telaNumero.display(self.numero)

    def divNumero(self):
        self.operacao = '/'
        self.resultado = self.numero
        self.numero = 0
        self.telaNumero.display(self.numero)

    def resolver(self):
        if self.operacao == '+':
            self.resultado = self.resultado + self.numero
        elif self.operacao == '-':
            self.resultado = self.resultado - self.numero
        elif self.operacao == '*':
            self.resultado = self.resultado * self.numero
        elif self.operacao == '/':
            self.resultado = self.resultado / self.numero

        self.numero = self.resultado
        
        self.telaNumero.display(self.resultado)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btnMais.setText(_translate("MainWindow", "+"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnMenos.setText(_translate("MainWindow", "-"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btnDivide.setText(_translate("MainWindow", "/"))
        self.btn10.setText(_translate("MainWindow", "0"))
        self.btn100.setText(_translate("MainWindow", "00"))
        self.btnVezes.setText(_translate("MainWindow", "*"))
        self.btnIgual.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
